### ISSUE TITLE
Ошибка запуска.

### ISSUE THREAD

**Issue by ur4ltz** [MyRequiem/spman#1]
Вот что происходит.

Устанавил из slackbuild, все прошло гладко но при первом запуске вылазит ошибка.

➜  spman spman --help
Traceback (most recent call last):
  File "/usr/sbin/spman", line 38, in <module>
    sys.exit(start())
  File "/usr/sbin/spman", line 33, in start
    check_main_deps()
  File "/usr/lib/python3.6/site-packages/spman/checkmaindeps.py", line 41, in check_main_deps
    if not pkgs.find_pkgs_on_system(dep):
  File "/usr/lib/python3.6/site-packages/spman/pkgs.py", line 40, in find_pkgs_on_system
    if self.get_parts_pkg_name(pkg)[0] == pkg_name:
  File "/usr/lib/python3.6/site-packages/spman/pkgs.py", line 62, in get_parts_pkg_name
    arch = parts[-2]
IndexError: list index out of range

Препробовал все ключи ошибка таже самая.
Проверил конфиги, на всякий случай создал сам пути.

**Comment by MyRequiem** [comment]
Скорее всего в вашей системе какой-то бардак творится в /var/log/packages/
Директория должна содержать только файлы именованные по названиям установленных пакетов, т.е.
имя_пакета-версия-архитектура-сборочный_тэг. Других файлов там просто не должно быть, хотя они могут там появится например при некорректном удалении какого-либо пакета из системы.

В любом случае спасибо. В конце недели  при обновлении репозитория на slackbuilds.org (обычно пятница-суббота) добавлю проверку на корректность содержимого /var/log/packages/

**Comment by ur4ltz** [comment]
Благодарю!
Обновился к 1.5.2 и сразу стало понятно в чем дело, в /var/log/packages/ бардака не было (я как-то по не знанию там все почистил).
Пришлось установить "coreutils-8.25-i586-2  diffutils-3.3-i486-1  pkgtools-14.2-noarch-10" и программа ожила.
С её помощю нашол кое что ещё на что стоит мне обратить внимание (отсутствие некоторых либ).

**Comment by MyRequiem** [comment]
Нельзя там ничего чистить, иначе нарушается сама идея организации пакетов в Slackware :)
